apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app-gke
  template:
    metadata:
      labels:
        app: fastapi-app-gke
    spec:
      containers:
        - name: fastapi-app-gke
          image: asia-south1-docker.pkg.dev/tasktwochaitanya/fastapi-repo/y-fastapi-image:latest
          ports:
            - containerPort: 80
          env:
            - name: db_name
              value: task_database  # <-- Replace with your MongoDB database name
            - name: mongo_uri
              value: mongodb+srv://thinkingcap1130:Chaitanya1130@cluster0.2ogyjhu.mongodb.net/task_database # <-- Add your MongoDB URI