apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: fastapi-app-gke
    newName: asia-south1-docker.pkg.dev/tasktwochaitanya/fastapi-repo/y-fastapi-image
    newTag: latest
